server.port=8081

# DATASOURCE for SQLite
spring.datasource.url=jdbc:sqlite:employee.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.sqlite.hibernate.dialect.SQLiteDialect

sec.config.allowedOrigins = *
spring.application.name = Employee APIs

# Hibernate
# The SQL dialect makes Hibernate generate better SQL for the chosen database
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = create-drop
# Hibernate logging for dev environment
logging.level.org.hibernate.SQL=info
logging.level.org.hibernate.type=info

logging.level.org.springframework.web= DEBUG
